title: '2. Settings'
data:
  nav_items:
    - Home
    - Contact
  homepage_content:
    - skills
    - about
  skills:
    - html
    - css
    - javascript
    - shopify
    - liquid
    - sass
    - statamic
    - git
  enable_messages:
    - blog-card
  blog_message_text: 'More coming soon!'
  projects_message_text: 'More coming soon!'
