sections:
  global:
    display: Global
    fields:
      -
        handle: nav_items
        field:
          inline: false
          options:
            Home: Home
            Projects: Projects
            Blog: Blog
            Contact: Contact
          display: 'Nav Items'
          type: checkboxes
          icon: checkboxes
          listable: hidden
  homepage:
    display: Homepage
    fields:
      -
        handle: homepage_content
        field:
          inline: false
          options:
            skills: Skills
            projects: Projects
            blog: Blog
            about: About
          display: 'Homepage content'
          type: checkboxes
          icon: checkboxes
          listable: hidden
      -
        handle: skills
        field:
          inline: false
          options:
            html: HTML
            css: CSS
            javascript: JavaScript
            shopify: Shopify
            liquid: Liquid
            sass: Sass
            craft-cms: 'Craft CMS'
            statamic: Statamic
            git: Git
            jquery: jQuery
            npm: NPM
            webpack: Webpack
          display: Skills
          type: checkboxes
          icon: checkboxes
          listable: hidden
  coming_soon_messages:
    display: 'Coming soon messages'
    fields:
      -
        handle: enable_messages
        field:
          inline: false
          options:
            blog-card: 'Blog card'
            projects-card: 'Projects card'
          display: 'Enable messages'
          type: checkboxes
          icon: checkboxes
          listable: hidden
      -
        handle: blog_message_text
        field:
          type: text
      -
        handle: projects_message_text
        field:
          type: text
  contact_form:
    display: 'Contact form'
    fields:
      -
        handle: enable_contact_form
        field:
          display: 'Enable contact form'
          type: toggle
          icon: toggle
          listable: hidden
